apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app

spec: 
  replicas: 3
  selector:
   matchLabels: 
    app: app-1
  
  template:
    metadata:
      labels:
        app: app-1
  
    spec:
      containers:
        - name: web-1
          image: zabihulla01/app1
          ports:
           -  containerPort: 80
          env:
          - name: ENV 
            valumeFrom:
              configMapKeyRef:
                name: app-config
                key: ENV 
          - name: data
            valumeFrom: 
              secretKeyRef:
                name: data
                key: password
          volumeMounts:
          - name: storage
            persistentVolumeClaim:
              claimName: pvc
